//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomQuotesPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomQuotesPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[custom_Quotes]    Script Date: 9/4/2019 4:02:25 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[custom_Quotes](
        ///	[QuoteId] [int] IDENTITY(1,1) NOT NULL,
        ///	[UserId] [int] NULL,
        ///	[Author] [nvarchar](255) NOT NULL,
        ///	[Website] [nvarchar](255) NULL,
        ///	[Content] [nvarchar](max) NULL,
        ///	[CreatedDate] [datetime] NULL,
        /// CONSTRAINT [PK_custom_Quotes] PRIMARY KEY CLUSTERED 
        ///(
        ///	[QuoteId] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create_custom_quotes {
            get {
                return ResourceManager.GetString("create_custom_quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[custom_Quotes]    Script Date: 9/4/2019 4:06:16 PM ******/
        ///DROP TABLE [dbo].[custom_Quotes]
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string drop_custom_quotes {
            get {
                return ResourceManager.GetString("drop_custom_quotes", resourceCulture);
            }
        }
    }
}
